import 'package:flutter/material.dart';

class TrendingPage extends StatelessWidget {
  final List<Map<String, dynamic>> trendingHostels = [
    {
      'name': 'Sunrise Hostel',
      'image': 'https://via.placeholder.com/150',
      'address': 'New Baneshwor, Kathmandu',
      'description': 'A peaceful and secure place with great amenities.',
      'rating': 4.5,
      'views': 1200,
      'warden': 'Mr. Sharma',
      'contact': '9841234567',
      'status': 'Active',
      'numberOfRooms': 20,
      'wifiAvailable': true,
      'hasParking': true,
      'hasCafeteria': false,
      'isAvailable': true,
    },
    {
      'name': 'CityView PG',
      'image': 'https://via.placeholder.com/150',
      'address': 'Putalisadak, Kathmandu',
      'description': 'Modern PG for students and working professionals.',
      'rating': 4.2,
      'views': 980,
      'warden': 'Mrs. K.C.',
      'contact': '9801234567',
      'status': 'Active',
      'numberOfRooms': 15,
      'wifiAvailable': true,
      'hasParking': false,
      'hasCafeteria': true,
      'isAvailable': false,
    },
      {
      'name': 'Sunrise Hostel',
      'image': 'https://via.placeholder.com/150',
      'address': 'New Baneshwor, Kathmandu',
      'description': 'A peaceful and secure place with great amenities.',
      'rating': 4.5,
      'views': 1200,
      'warden': 'Mr. Sharma',
      'contact': '9841234567',
      'status': 'Active',
      'numberOfRooms': 20,
      'wifiAvailable': true,
      'hasParking': true,
      'hasCafeteria': false,
      'isAvailable': true,
    },
    {
      'name': 'CityView PG',
      'image': 'https://via.placeholder.com/150',
      'address': 'Putalisadak, Kathmandu',
      'description': 'Modern PG for students and working professionals.',
      'rating': 4.2,
      'views': 980,
      'warden': 'Mrs. K.C.',
      'contact': '9801234567',
      'status': 'Active',
      'numberOfRooms': 15,
      'wifiAvailable': true,
      'hasParking': false,
      'hasCafeteria': true,
      'isAvailable': false,
    },  {
      'name': 'Sunrise Hostel',
      'image': 'https://via.placeholder.com/150',
      'address': 'New Baneshwor, Kathmandu',
      'description': 'A peaceful and secure place with great amenities.',
      'rating': 4.5,
      'views': 1200,
      'warden': 'Mr. Sharma',
      'contact': '9841234567',
      'status': 'Active',
      'numberOfRooms': 20,
      'wifiAvailable': true,
      'hasParking': true,
      'hasCafeteria': false,
      'isAvailable': true,
    },
    {
      'name': 'CityView PG',
      'image': 'https://via.placeholder.com/150',
      'address': 'Putalisadak, Kathmandu',
      'description': 'Modern PG for students and working professionals.',
      'rating': 4.2,
      'views': 980,
      'warden': 'Mrs. K.C.',
      'contact': '9801234567',
      'status': 'Active',
      'numberOfRooms': 15,
      'wifiAvailable': true,
      'hasParking': false,
      'hasCafeteria': true,
      'isAvailable': false,
    },  {
      'name': 'Sunrise Hostel',
      'image': 'https://via.placeholder.com/150',
      'address': 'New Baneshwor, Kathmandu',
      'description': 'A peaceful and secure place with great amenities.',
      'rating': 4.5,
      'views': 1200,
      'warden': 'Mr. Sharma',
      'contact': '9841234567',
      'status': 'Active',
      'numberOfRooms': 20,
      'wifiAvailable': true,
      'hasParking': true,
      'hasCafeteria': false,
      'isAvailable': true,
    },
    {
      'name': 'CityView PG',
      'image': 'https://via.placeholder.com/150',
      'address': 'Putalisadak, Kathmandu',
      'description': 'Modern PG for students and working professionals.',
      'rating': 4.2,
      'views': 980,
      'warden': 'Mrs. K.C.',
      'contact': '9801234567',
      'status': 'Active',
      'numberOfRooms': 15,
      'wifiAvailable': true,
      'hasParking': false,
      'hasCafeteria': true,
      'isAvailable': false,
    },  {
      'name': 'Sunrise Hostel',
      'image': 'https://via.placeholder.com/150',
      'address': 'New Baneshwor, Kathmandu',
      'description': 'A peaceful and secure place with great amenities.',
      'rating': 4.5,
      'views': 1200,
      'warden': 'Mr. Sharma',
      'contact': '9841234567',
      'status': 'Active',
      'numberOfRooms': 20,
      'wifiAvailable': true,
      'hasParking': true,
      'hasCafeteria': false,
      'isAvailable': true,
    },
    {
      'name': 'CityView PG',
      'image': 'https://via.placeholder.com/150',
      'address': 'Putalisadak, Kathmandu',
      'description': 'Modern PG for students and working professionals.',
      'rating': 4.2,
      'views': 980,
      'warden': 'Mrs. K.C.',
      'contact': '9801234567',
      'status': 'Active',
      'numberOfRooms': 15,
      'wifiAvailable': true,
      'hasParking': false,
      'hasCafeteria': true,
      'isAvailable': false,
    },  {
      'name': 'Sunrise Hostel',
      'image': 'https://via.placeholder.com/150',
      'address': 'New Baneshwor, Kathmandu',
      'description': 'A peaceful and secure place with great amenities.',
      'rating': 4.5,
      'views': 1200,
      'warden': 'Mr. Sharma',
      'contact': '9841234567',
      'status': 'Active',
      'numberOfRooms': 20,
      'wifiAvailable': true,
      'hasParking': true,
      'hasCafeteria': false,
      'isAvailable': true,
    },
    {
      'name': 'CityView PG',
      'image': 'https://via.placeholder.com/150',
      'address': 'Putalisadak, Kathmandu',
      'description': 'Modern PG for students and working professionals.',
      'rating': 4.2,
      'views': 980,
      'warden': 'Mrs. K.C.',
      'contact': '9801234567',
      'status': 'Active',
      'numberOfRooms': 15,
      'wifiAvailable': true,
      'hasParking': false,
      'hasCafeteria': true,
      'isAvailable': false,
    },
    // Add more hostels if needed...
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Trending Hostels'),
        centerTitle: true,
      ),
      body: Padding(
        padding: const EdgeInsets.all(8),
        child: GridView.builder(
          itemCount: trendingHostels.length,
          gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
            crossAxisCount: 2,
            mainAxisSpacing: 12,
            crossAxisSpacing: 12,
            childAspectRatio: 0.70, // Adjust based on content
          ),
          itemBuilder: (context, index) {
            final hostel = trendingHostels[index];
            return Card(
              elevation: 4,
              shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(12)),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  ClipRRect(
                    borderRadius:
                        const BorderRadius.vertical(top: Radius.circular(12)),
                    child: Image.network(
                      hostel['image'] ?? '',
                      height: 100,
                      width: double.infinity,
                      fit: BoxFit.cover,
                    ),
                  ),
                  Expanded(
                    child: Padding(
                      padding: const EdgeInsets.all(8),
                      child: SingleChildScrollView(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(hostel['name'] ?? '',
                                style: const TextStyle(
                                    fontWeight: FontWeight.bold)),
                            const SizedBox(height: 4),
                            Text(hostel['address'] ?? '',
                                style: const TextStyle(fontSize: 12)),
                            Text('Warden: ${hostel['warden'] ?? 'N/A'}',
                                style: const TextStyle(fontSize: 12)),
                            Text('Contact: ${hostel['contact'] ?? 'N/A'}',
                                style: const TextStyle(fontSize: 12)),
                            Text('Status: ${hostel['status']}',
                                style: const TextStyle(fontSize: 12)),
                            Text('Rooms: ${hostel['numberOfRooms']}',
                                style: const TextStyle(fontSize: 12)),
                            Text('WiFi: ${hostel['wifiAvailable'] ? "Yes" : "No"}'),
                            Text('Parking: ${hostel['hasParking'] ? "Yes" : "No"}'),
                            Text('Cafeteria: ${hostel['hasCafeteria'] ? "Yes" : "No"}'),
                            Text('Available: ${hostel['isAvailable'] ? "Yes" : "No"}'),
                            const SizedBox(height: 4),
                            Text(
                              hostel['description'] ?? '',
                              maxLines: 2,
                              overflow: TextOverflow.ellipsis,
                              style: const TextStyle(fontSize: 11),
                            ),
                            const SizedBox(height: 6),
                            Row(
                              children: [
                                const Icon(Icons.star,
                                    size: 14, color: Colors.orange),
                                Text('${hostel['rating'] ?? '0.0'}',
                                    style: const TextStyle(fontSize: 12)),
                                const Spacer(),
                                const Icon(Icons.visibility, size: 14),
                                Text('${hostel['views'] ?? 0}',
                                    style: const TextStyle(fontSize: 12)),
                              ],
                            ),
                          ],
                        ),
                      ),
                    ),
                  ),
                ],
              ),
            );
          },
        ),
      ),
    );
  }
}
